### ISSUE TITLE
performance issue with huge subtree

### ISSUE THREAD

**Issue by vesparny** [vesparny/statty#12]
### the problem

I've tried to implement the [redux tree-view](https://github.com/reactjs/redux/tree/master/examples/tree-view) example with statty and I've noticed a big performance impact in such a scenario.

Problem being that subscribing 1000+ nodes to state changes forces a rerender of the entire tree every  time.

Personally I've never hit this use-case in real apps I've built but I think investigating possible solutions is probably worth.

I've created a codesanbox to showcase the problem.

https://codesandbox.io/s/k96o8wpy5o

As you can see all the tree rerenders on every state change

### possible solution

ATM we call `setState` on every state change. I was wondering if there is a way to avoid this behaviour.

As we use a `select` function to get only the state we need for rendering  the single node and its children, we could probably use the same select function to get the old state, do a shallow comparison with the new one, and `setState()` only if the comparison returns false.

This way I think only nodes interested by the state change will render, instead of the whole tree.

@kentcdodds and @busypeoples any thoughts?

**Comment by busypeoples** [comment]
Will look into the problem. Maybe can provide some insights into the problem.

**Comment by vesparny** [comment]
have a look at this codesanbox.

https://codesandbox.io/s/3y146z2qop

I changed 2 things

* in statty I do a shallow comparison before setting state
* I leverage sCU in the `NodeContainer` component

I kind of like this solution because it has a very little impact on the library itself, and it give the user a chance to optimise further with sCU if needed.

**Comment by kentcdodds** [comment]
Your solution sounds great to me because it optimizes internally as best you can and still allows the user to optimise further as you mention :+1:

Good work!

**Comment by vesparny** [comment]
Yep.

I will probably create PR soon with some more tests.

@kentcdodds Besides that... As you've seen I copied/pasted the src folder in the codesandbox.
Do you have any tip for avoiding this when I just want to try new things without publishing to npm?

**Comment by kentcdodds** [comment]
Unfortunately I don't know of any other way to do it. You _could_ publish a version called `0.0.0-test-version.0` and make sure to add `--tag test` so it doesn't get used as `latest`...

**Comment by busypeoples** [comment]
@vesparny Yes, this seems to be a very sensible approach. As @kentcdodds already mentioned, a good internal optimization and any further optimizations can be handled in user land.

**Comment by vesparny** [comment]
Ok guys thanks for your support. I'll make a PR for this.

**Comment by vesparny** [comment]
I' ve released `statty@2.0.0`.

* updaters now MUST return a new state object
* perf optim

@busypeoples thanks for your help

@kentcdodds when people complain about render prop being slow or not optimisable ==> https://codesandbox.io/s/3y146z2qop

😀
