### ISSUE TITLE
Synchronous actions / callback pattern?

### ISSUE THREAD

**Issue by ericdfields** [vesparny/statty#17]
What would be a reasonable way to implement a callback after an update function, such as closing a popover after an update action is triggered?

```
onClick={() => {
  update(myUpdater(value))
  closeThatSucka()
}
```

This works well enough for me because my second function doesn't relate to updating the statty store, but I could see needing it in the future.

```
onClick={() => {
  update(myUpdater(value),  closeThatSucka())
}
```

Feels more contemporary.

**Comment by vesparny** [comment]
Hi,

I would personally add a flag in the state object.

```js
{
  isPopupOpen: false
}
```

this way you can set it to false when you want to close it, and you do not need to leverage another updater function.

**Comment by ericdfields** [comment]
Thanks for responding. I’m already doing that, and I guess I can fold two updaters together — updateFromPopupAction + closePopup = updateFromPopupActionAndClose. This potentially couples the state of, say, a model provided from the server with the state of the UI which is subject to change based on design updates.

Thinking out loud, if there’s a design update, you’re updating code anyway, why not go ahead and modify your married updater function.

I’m not sure I’m convinced it’s right, but it’s what I’ll be doing :)

**Comment by vesparny** [comment]
Do you have any code to share for me to have a look?
