### ISSUE TITLE
Nested state

### ISSUE THREAD

**Issue by vesparny** [vesparny/statty#4]
I've been playing around with this library and I think it's ready to be promoted a little bit 😄 .

There is  codesanbox [here](https://codesandbox.io/s/o2rq7oJ0z) including the classic and simple counter example plus other more complex async interactions.

One of the things I really enjoyed using redux was reducers composition.
Since `statty` does not have a concept of `actions` nor `reducers`, dealing with nested state might become a bit cumbersome.
The reason is that updater functions get as unique parameter the whole state tree, that must be modified and returned to be then merged with the old state.

In my codesandbox I tried to use `Ramda` to ease state mutations, but I am not sure neither if I did it right (I started playing with Ramda like couple hours ago ) nor if there is potentially a better way for doing this at library level.

I know @busypeoples is the king of Ramda 😄 so he might be able to advice here.

I am basically looking for a good pattern to apply for state transitions more complex than a simple counter that increments/decrements.

Here another codesandbox containing only the `Wikipedia` example (just for clarity) you can play with.

https://codesandbox.io/s/mQJl3qB2G

```js
import React from 'react'
import Rx from 'rxjs'
import R from 'ramda'
import jsonp from 'jsonp'
import { State } from 'statty'

// updaters
const loadPosts = state => ({ wiki: R.evolve({ loading: R.T })(state.wiki) })
const updateTopic = topic => state => ({
  wiki: R.evolve({ topic: R.always(topic) })(state.wiki)
})
const postsLoaded = data => state => ({
  wiki: R.evolve({
    posts: R.always(R.ifElse(Array.isArray, R.identity, R.always([]))(data)),
    loading: R.F
  })(state.wiki)
})

//selector
const getWikiSliceFromState = R.view(R.lensProp('wiki'))

class WikipediaContainer extends React.Component {
  render() {
    return (
      <State
        select={getWikiSliceFromState}
        children={(state, update) => <Wikipedia {...state} update={update} />}
      />
    )
  }
}

const request = topic => Rx.Observable.bindNodeCallback(jsonp)

const wikipediaService = update => {
  const eventsSubject = new Rx.Subject()
  return {
    init(topic) {
      eventsSubject
        .startWith(topic)
        .debounceTime(300)
        .distinctUntilChanged()
        .do(() => update(loadPosts))
        .switchMap(t =>
          request(t)(
            `https://en.wikipedia.org/w/api.php?action=opensearch&format=json&search=${t}`,
            null
          )
        )
        .subscribe(data => update(postsLoaded(data[1])))
    },
    updateTopic(topic) {
      eventsSubject.next(topic)
    }
  }
}

class Wikipedia extends React.Component {
  service = wikipediaService(this.props.update)

  componentDidMount() {
    this.service.init(this.props.topic)
  }

  componentWillReceiveProps(nextProps) {
    this.service.updateTopic(nextProps.topic)
  }

  render() {
    const { loading, topic, posts, update } = this.props
    return (
      <div>
        <input
          type="text"
          onChange={e => update(updateTopic(e.target.value))}
          value={topic}
        />
        {loading
          ? <div>loading...</div>
          : <div>
              {posts.map((el, i) =>
                <div key={i}>
                  {el}
                </div>
              )}
            </div>}
      </div>
    )
  }
}

export default WikipediaContainer

```

where the initial state is

```js
import React from 'react'
import { render } from 'react-dom'
import Wikipedia from './Wikipedia'
import { Provider } from 'statty'


const initialState = {
  wiki: {
    topic: 'roger federer',
    posts: [],
    loading: true
  }
}

const App = () =>
  <Provider state={initialState}>
    <div>
      <h4>Wikipedia searchbox using Rx</h4>
      <Wikipedia />
    </div>
  </Provider>

render(<App />, document.getElementById('root'))

```

thanks a lot to anybody willing to contribute to the discussion 👍

**Comment by busypeoples** [comment]
I like have a look later on today!

**Comment by vesparny** [comment]
Also @jxnblk opinion, who worked on `funcup` I got inspiration from, would be highly appreciated

**Comment by busypeoples** [comment]
This looks really interesting!

**Comment by vesparny** [comment]
I think I miss something like combineReducers.
An easy way to compose updaters and return final state

**Comment by marcusradell** [comment]
(Long rant with random thoughts. I don't expect you to find much value, but there's still a chance!)

I have two OSS repos that do composition of state with rxjs and react:

* (A bit more boilerplate and advanced/researchy) https://github.com/marcusnielsen/reactive-tournament/tree/development/src/components/button
* (Recommended starting point. Simpler and more conventions.) https://github.com/LinasMatkasse/planck-state/tree/master/examples/src/text-field

Planck-state hides rxjs pretty well.
You can create simple sync actions by giving a pure updater (reducer) function. The updater function is used to generate a rxjs Subject that acts as an action creator and an action stream. The action streams are merged and scanned/reduced into a state stream.

If you want to do an async epic, you create an normal updater for the loading state, another updater for success response, and a third for error response. Then you give it a promise-based service as the last part, and planck-state connects them together. You need to keep response under the key `data` and `errors`.

I've just started with forms as well, but will polish it some more. You give a serialisable props-tree that generates the form. Basically it's mostly rxjs `withLatestFrom` putting state streams together.

Usually though, you won't need other components state, and then you can just create components inside a parent component, and send the stateful child views as props to the parent view. In the future, sending a set of children to planck-state should be enough.

**Comment by vesparny** [comment]
@marcusnielsen thanks a lot for your hint.
At this stage I think I'd rather prefer to keep `statty` as lean and flexible as possible.
I do not want to add more complexity with rxjs.
